SRC_HC_OPTS        = -O0 -H64m -fPIC
GhcStage1HcOpts    = -O -fPIC
GhcStage2HcOpts    = -O0 -fPIC
GhcLibHcOpts       = -O -fPIC
BUILD_PROF_LIBS    = NO
SplitObjs          = NO
SplitSections      = NO
HADDOCK_DOCS       = NO
BUILD_SPHINX_HTML  = NO
BUILD_SPHINX_PDF   = NO
BUILD_MAN          = NO
